apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp-redis
  template:
    metadata:
      labels:
        app: myapp-redis
    spec:
      containers:
      - name: myap-redis
        image: docker.io/satankumaryadav/redis-app:latest 
        #imagePullPolicy: Never # it is  for local image pull instead of docker hub
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
